stages:
- test

sast:
  stage: test

include:
- template: Security/SAST.gitlab-ci.yml

test:
  stage: test
  image: gradle:8.14-jdk21-alpine
  variables:
    FF_NETWORK_PER_BUILD: "true"
    DOCKER_HOST: "tcp:docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:dind
      command: [ "--host=tcp://0.0.0.0:2375", "--tls=false" ]
  before_script:
    - echo "Installing Docker client..."
    - apk add --no-cache docker-cli
    - echo "Waiting for Docker daemon to be ready..."
    - |
      retry=0
      while ! docker info >/dev/null 2>&1; do
        if [ $retry -ge 30 ]; then
          echo "Docker daemon did not start within 30 seconds."
          exit 1
        fi
        retry=$((retry+1))
        sleep 1
      done
    - echo "Docker daemon is ready."
  script:
    - ./gradlew build
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/libs/nucleus.jar
  rules:
    - if: $CI_COMMIT_TAG == null
