language: java
jdk:
  - openjdk21

# Use Ubuntu 22.04 to get Java 21 support
# Sudo privileges are needed for Docker
sudo: required
dist: jammy

services:
  - docker

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

script:
  - ./gradlew build
  - docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
  - docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:latest

after_success:
  - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
  - docker push $IMAGE_NAME:$TRAVIS_COMMIT
  - docker push $IMAGE_NAME:latest

env:
  global:
    - IMAGE_NAME=ghcr.io/${TRAVIS_REPO_SLUG}
