#!/usr/bin/env bash
awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered"  }' ./build/reports/jacoco/test/jacocoTestReport.csv
