spring:
  application:
    name: Nucleus
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        globally_quoted_identifiers: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: iterator.nucleus.JsonRedissonRegionFactory
          redisson:
            fallback: true
            config: redisson.yml
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: NucleusScheduler
            instanceId: AUTO
          jobStore:
            isClustered: true
            clusterCheckinInterval: 20000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          threadPool:
            threadCount: 5
            threadPriority: 5

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - auditevents
    access:
      default: none
  endpoint:
    health:
      access: read_only
    auditevents:
      access: read_only

logging:
  level:
    ROOT: ERROR
    iterator.nucleus: INFO

nucleus:
  defaults:
    kafka:
      number-of-partitions: 10
      replication-factor: 3
      retry:
        max-attempts: 5
        delay: 1000
        multiplier: 2.0
        max-delay: 30000

---

spring:
  config:
    activate:
      on-profile: minikube

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted

---

spring:
  config:
    activate:
      on-profile: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted

---

spring:
  config:
    activate:
      on-profile: api-test
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

nucleus:
  defaults:
    kafka:
      number-of-partitions: 1
      replication-factor: 1
      retry:
        max-attempts: 3
        delay: 10
        multiplier: 1.0
        max-delay: 10
