apiVersion: v1
kind: Namespace
metadata:
  name: nucleus

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nucleus-config
  namespace: nucleus
data:
  SPRING_PROFILES_ACTIVE: "minikube"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nucleus
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: nucleus
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "nucleus"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "nucleus"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nucleus
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: nucleus
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: nucleus
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: nucleus
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:8.10.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: nucleus
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: nucleus
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:8.10.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LOG_FLUSH_INTERVAL_MESSAGES
              value: "9223372036854775807"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-service
  namespace: nucleus
  labels:
    app: nucleus-service
spec:
  selector:
    matchLabels:
      app: nucleus-service
  replicas: 1
  template:
    metadata:
      labels:
        app: nucleus-service
    spec:
      containers:
        - name: nucleus-service
          image: iterator/nucleus:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: nucleus-config
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/nucleus"
            - name: SPRING_DATASOURCE_USERNAME
              value: "nucleus"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
              httpHeaders:
                - name: X-Client-ID
                  value: k8s-readiness-probe
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
              httpHeaders:
                - name: X-Client-ID
                  value: k8s-readiness-probe
            initialDelaySeconds: 10
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: nucleus-service
  namespace: nucleus
spec:
  selector:
    app: nucleus-service
  ports:
    - port: 8080
      protocol: TCP
